# Configuracion del servidor SSH

# Nadie entra directamente como administrador
PermitRootLogin no

# Se permite entrar con contrasena
PasswordAuthentication yes

# Sin mensajes estandar al entrar
PrintMotd no
PrintLastLog no
